/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileTypeEditor.java
 *
 * Created on Sep 5, 2010, 1:32:40 PM
 */

package com.baseoneonline.java.mediabrowser.gui;

import java.util.ArrayList;

import com.baseoneonline.java.mediabrowser.core.FileType;
import com.baseoneonline.java.mediabrowser.util.ArrayListModel;

/**
 * 
 * @author bmod
 */
public class FileTypeListEditor extends javax.swing.JPanel {

	private final ArrayListModel<FileType> fileTypes =
			new ArrayListModel<FileType>();

	private final ArrayList<Listener> listeners = new ArrayList<Listener>();

	/** Creates new form FileTypeEditor */
	public FileTypeListEditor() {
		initComponents();

		fileTypeEditor.addListener(new FileTypeEditor.Listener() {

			@Override
			public void dataChanged() {
				System.out.println("DataChanged");
				fileTypes.set(listFileTypes.getSelectedIndex(),
						fileTypeEditor.getFileType());
				fireDataChanged();
			}
		});
	}

	public void addListener(final Listener l) {
		if (!listeners.contains(l))
			listeners.add(l);
	}

	public void removeListener(final Listener l) {
		listeners.remove(l);
	}

	public void setFileTypes(final ArrayList<FileType> types) {
		fileTypes.clear();
		for (final FileType t : types) {
			fileTypes.add(t);
		}
	}

	public ArrayList<FileType> getFileTypes() {
		return fileTypes;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		listFileTypes = new javax.swing.JList();
		btAdd = new javax.swing.JButton();
		btRemove = new javax.swing.JButton();
		fileTypeEditor =
				new com.baseoneonline.java.mediabrowser.gui.FileTypeEditor();

		listFileTypes.setModel(fileTypes);
		listFileTypes
				.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
					@Override
					public void valueChanged(
							final javax.swing.event.ListSelectionEvent evt) {
						listFileTypesValueChanged(evt);
					}
				});
		jScrollPane1.setViewportView(listFileTypes);

		btAdd.setText("Add");
		btAdd.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(final java.awt.event.ActionEvent evt) {
				btAddActionPerformed(evt);
			}
		});

		btRemove.setText("Remove");
		btRemove.setEnabled(false);
		btRemove.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(final java.awt.event.ActionEvent evt) {
				btRemoveActionPerformed(evt);
			}
		});

		fileTypeEditor.setBorder(javax.swing.BorderFactory
				.createTitledBorder("File Type Properties"));
		fileTypeEditor.setEnabled(false);

		final javax.swing.GroupLayout layout =
				new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btRemove)
												.addComponent(
														btAdd,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														71, Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										145,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(fileTypeEditor,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														fileTypeEditor,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														327, Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		btAdd)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		btRemove)))
								.addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	private void btAddActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btAddActionPerformed
		final FileType type = new FileType();
		type.name = "New Filetype";
		fileTypes.add(type);
		listFileTypes.setSelectedValue(type, true);
		fireDataChanged();

	}// GEN-LAST:event_btAddActionPerformed

	private void listFileTypesValueChanged(
			final javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_listFileTypesValueChanged
		final int idx = listFileTypes.getSelectedIndex();
		final boolean enable = idx != -1;
		btRemove.setEnabled(enable);
		fileTypeEditor.setEnabled(enable);
		if (!enable)
			return;
		final FileType type = fileTypes.get(idx);
		fileTypeEditor.setFileType(type);
	}// GEN-LAST:event_listFileTypesValueChanged

	private void btRemoveActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btRemoveActionPerformed
		for (final int idx : listFileTypes.getSelectedIndices()) {
			fileTypes.remove(idx);
		}
		fireDataChanged();
	}// GEN-LAST:event_btRemoveActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btAdd;
	private javax.swing.JButton btRemove;
	private com.baseoneonline.java.mediabrowser.gui.FileTypeEditor fileTypeEditor;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JList listFileTypes;

	// End of variables declaration//GEN-END:variables

	private void fireDataChanged() {
		for (final Listener l : listeners) {
			l.dataChanged();
		}
	}

	public static interface Listener {
		public void dataChanged();
	}
}
