/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewApplication.java
 *
 * Created on Sep 10, 2010, 12:55:30 AM
 */
package com.baseoneonline.java.mediabrowser.gui;

import com.baseoneonline.java.mediabrowser.core.Database;
import com.baseoneonline.java.mediabrowser.core.MediaScanner;
import com.baseoneonline.java.mediabrowser.core.SimpleDataView;
import com.baseoneonline.java.mediabrowser.core.TreeModelAdapter;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.tree.TreeModel;

/**
 *
 * @author bmod
 */
public class MainInterface extends javax.swing.JFrame {

	private TreeModel treeModel;

	/** Creates new form NewApplication */
	public MainInterface() {
		initComponents();

		treeModel = new TreeModelAdapter(new SimpleDataView(Database.get()));
		jTree1.setModel(treeModel);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        miScanLibrary = new javax.swing.JMenuItem();
        miSettings = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jScrollPane1.setViewportView(jTree1);

        fileMenu.setText("File");

        miScanLibrary.setText("Scan Library");
        miScanLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miScanLibraryActionPerformed(evt);
            }
        });
        fileMenu.add(miScanLibrary);

        miSettings.setText("Settings....");
        miSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSettingsActionPerformed(evt);
            }
        });
        fileMenu.add(miSettings);

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        fileMenu.add(miExit);

        menuBar.add(fileMenu);

        helpMenu.setText("Help");

        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
		System.exit(0);
    }//GEN-LAST:event_miExitActionPerformed

	private void miScanLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miScanLibraryActionPerformed
		final MediaScanner scanner = new MediaScanner(Database.get());
		ScannerDialog dialog = ScannerDialog.get(scanner);
		scanner.scan(Database.get().getMediaSources());
		dialog.setLocationRelativeTo(this);
		dialog.setVisible(true);

	}//GEN-LAST:event_miScanLibraryActionPerformed

	private void miSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSettingsActionPerformed
		SettingsDialog dialog = SettingsDialog.get(Database.get());
		dialog.setLocationRelativeTo(this);
		dialog.setVisible(true);
	}//GEN-LAST:event_miSettingsActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (Exception e) {
			Logger.getLogger(MainInterface.class.getName()).info(e.getLocalizedMessage());
		}
		java.awt.EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				new MainInterface().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miScanLibrary;
    private javax.swing.JMenuItem miSettings;
    // End of variables declaration//GEN-END:variables
}
