/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScannerDialog.java
 *
 * Created on Sep 5, 2010, 11:45:58 PM
 */

package com.baseoneonline.java.mediabrowser.gui;

import java.util.List;

import com.baseoneonline.java.mediabrowser.core.MediaFile;
import com.baseoneonline.java.mediabrowser.core.MediaScanner;
import com.baseoneonline.java.mediabrowser.core.MediaScanner.Status;

/**
 * 
 * @author bmod
 */
public class ScannerDialog extends javax.swing.JDialog {

	private static ScannerDialog instance;

	/**
	 * Creates new form ScannerDialog
	 * 
	 * @param scanner
	 */
	private ScannerDialog(final java.awt.Frame parent, final boolean modal,
			final MediaScanner scanner) {
		super(parent, modal);
		initComponents();

		progressBar.setIndeterminate(true);

		scanner.addListener(new MediaScanner.Listener() {

			@Override
			public void process(final List<MediaFile> files) {
				// Show last file
				if (files.size() > 0)
					lbCurrentFile.setText(files.get(files.size() - 1).file);

				lbFilesFound.setText("" + scanner.getMediaFiles().size());
			}

			@Override
			public void statusChanged(final Status msg) {
				lbStatus.setText(msg.toString());
				switch (msg) {
				case Done:
					lbFilesFound.setText("" + scanner.getMediaFiles().size());
					progressBar.setIndeterminate(false);
					progressBar.setEnabled(false);
					lbCurrentFile.setText(null);
					break;

				default:
					break;
				}
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		progressBar = new javax.swing.JProgressBar();
		jLabel1 = new javax.swing.JLabel();
		lbFilesFound = new javax.swing.JLabel();
		lbStatus = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		lbCurrentFile = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Media Scanner");

		jLabel1.setText("Files found:");

		lbFilesFound.setText("0");

		lbStatus.setText("Idle");

		jLabel4.setText("Current file:");

		lbCurrentFile.setText("...");

		final javax.swing.GroupLayout layout =
				new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														lbStatus,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														380, Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addGap(18, 18,
																		18)
																.addComponent(
																		lbFilesFound,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		306,
																		Short.MAX_VALUE))
												.addComponent(
														progressBar,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														380, Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel4)
																.addGap(18, 18,
																		18)
																.addComponent(
																		lbCurrentFile,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		304,
																		Short.MAX_VALUE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(lbStatus)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(progressBar,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(lbCurrentFile))
								.addGap(8, 8, 8)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(lbFilesFound))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(final String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				final ScannerDialog dialog =
						new ScannerDialog(new javax.swing.JFrame(), true, null);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(final java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel lbCurrentFile;
	private javax.swing.JLabel lbFilesFound;
	private javax.swing.JLabel lbStatus;
	private javax.swing.JProgressBar progressBar;

	// End of variables declaration//GEN-END:variables

	public static ScannerDialog get(final MediaScanner scanner) {
		if (null == instance)
			instance = new ScannerDialog(null, true, scanner);
		instance.setVisible(true);
		return instance;
	}

}
