/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScannerDialog.java
 *
 * Created on Sep 5, 2010, 11:45:58 PM
 */

package com.baseoneonline.java.mediabrowser.gui;

import com.baseoneonline.java.mediabrowser.core.Database;
import java.util.List;

import com.baseoneonline.java.mediabrowser.core.MediaFile;
import com.baseoneonline.java.mediabrowser.core.MediaScanner;
import com.baseoneonline.java.mediabrowser.core.MediaScanner.Status;
import java.awt.Component;
import javax.swing.JFrame;

/**
 * 
 * @author bmod
 */
public class ScannerDialog extends javax.swing.JDialog {

	private static ScannerDialog instance;

	private MediaScanner scanner;

	/**
	 * Creates new form ScannerDialog
	 * 
	 * @param scanner
	 */
	private ScannerDialog(final java.awt.Frame parent, final boolean modal,
			final MediaScanner scanner) {
		super(parent, modal);
		initComponents();

		this.scanner = scanner;
		scanner.addListener(scannerListener);
	}

	MediaScanner.Listener scannerListener = new MediaScanner.Listener() {

			@Override
			public void process(final List<MediaFile> files, final int totalScanned) {
				// Show last file
				if (files.size() > 0)
					lbCurrentFile.setText(files.get(files.size() - 1).file);

				lbFilesFound.setText("" + totalScanned);
				pack();
			}

			@Override
			public void statusChanged(final Status status, final int totalScanned) {
				lbStatus.setText(status.toString());
				switch (status) {
				case Done:
					lbFilesFound.setText("" + totalScanned);
					progressBar.setIndeterminate(false);
					progressBar.setEnabled(false);
					lbCurrentFile.setText(null);
					break;

				default:
					break;
				}
				pack();
			}

		};

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        lbFilesFound = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbCurrentFile = new javax.swing.JLabel();
        btClose = new javax.swing.JButton();
        btStartScanning = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Media Scanner");

        progressBar.setEnabled(false);

        jLabel1.setText("Files found:");

        lbFilesFound.setText("0");

        lbStatus.setText("Idle");

        jLabel4.setText("Current file:");

        lbCurrentFile.setText("...");

        btClose.setText("Close");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        btStartScanning.setText("Start Scanning");
        btStartScanning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartScanningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lbFilesFound, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lbCurrentFile, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btStartScanning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                        .addComponent(btClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbCurrentFile))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbFilesFound))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClose)
                    .addComponent(btStartScanning))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btStartScanningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartScanningActionPerformed
		scanner.scan(Database.get().getMediaSources());
	}//GEN-LAST:event_btStartScanningActionPerformed

	private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
		
	}//GEN-LAST:event_btCloseActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(final String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				final ScannerDialog dialog =
						new ScannerDialog(new javax.swing.JFrame(), true, null);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(final java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btStartScanning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbCurrentFile;
    private javax.swing.JLabel lbFilesFound;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

	public static ScannerDialog get(final MediaScanner scanner, Component parent) {
		if (null == instance)
			instance = new ScannerDialog(null, true, scanner);
		if (null != parent)
			instance.setLocationRelativeTo(parent);
		instance.setVisible(true);
		return instance;
	}

}
