package com.baseoneonline.java.test.testMedia;

import javax.swing.JPanel;

public class ScannerStatusPanel extends JPanel {

	/** Creates new form ScannerStatusPanel */
	public ScannerStatusPanel() {
		initComponents();
	}

	public void setState(String msg) {
		lbState.setText(msg);
	}

	public void setMessage(String msg) {
		lbMessage.setText(msg);
	}

	public void setNumfiles(int n) {
		lbNumfiles.setText(n + "");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		lbState = new javax.swing.JLabel();
		lbMessage = new javax.swing.JLabel();
		lbNumfiles = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();

		setLayout(new java.awt.GridBagLayout());

		jLabel1.setText("State:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
		add(jLabel1, gridBagConstraints);

		jLabel2.setText("Details:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
		add(jLabel2, gridBagConstraints);

		lbState.setText("jLabel3");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		add(lbState, gridBagConstraints);

		lbMessage.setText("jLabel4");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		add(lbMessage, gridBagConstraints);

		lbNumfiles.setText("jLabel3");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		add(lbNumfiles, gridBagConstraints);

		jLabel4.setText("Files Scanned:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
		add(jLabel4, gridBagConstraints);
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel lbMessage;
	private javax.swing.JLabel lbNumfiles;
	private javax.swing.JLabel lbState;
	// End of variables declaration

}
